version: '3.4'

services:
  mongo:
    container_name: mongo
    image: mongo
    # environment:
    #   MONGO_INITDB_DATABASE: tripadvisor-db
    volumes:
      # - ./db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
      # - ./data:/data/db
      - tripadvisor-db-chris:/data/db
    ports:
      - 27017:27017
  thiscunninghamservice:
    container_name: app
    image: thiscunninghamservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:3001
    links:
      - mongo
volumes:
  tripadvisor-db-chris: