version: "2.1"
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: circleci/node:current
      - image: circleci/mongo:4.1.9
    steps:
      - checkout
      - run: npm install
      - run: npm run seed
      - run: npm run test
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'linting'
          command: npm run lint
workflows:
  run-unit-tests:
    jobs:
      - lint
      - test